### PR TITLE
Remove language validation

### PR DESCRIPTION
**Pull request by Daaarkling**

### CODE REVIEW

**Review by edgar-zigis — APPROVED** [review]
@saltanovas maybe it is worth to add here all supported languages? Because our frontend supports more of them than it is specified here.

**Comment by saltanovas** [comment]
@edgar-zigis got it. But does it worth to have a restriction here in our library? Frame page switches to default English automatically if not supported language code is provided.

**Review by edgar-zigis — APPROVED** [review]

**Comment by Daaarkling** [comment]
@saltanovas @edgar-zigis alright based on comments I've changed this PR to remove language validation.

**Review by saltanovas — APPROVED** [review]

**Comment by saltanovas** [comment]
@Daaarkling thanks for the contribution🥇💯

**Comment by edgar-zigis** [comment]
@Daaarkling 🇨🇿 rocks!

**Pull request merged**
